[alembic]
script_location = alembic
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s
prepend_sys_path = .
sqlalchemy.url = postgresql://user:password@localhost:5432/knowledgeflow

[post_write_hooks]
